theme = "yellowed"

[editor]
completion-trigger-len = 1
end-of-line-diagnostics = "hint"
auto-save = true
bufferline = "multiple"
line-number = "relative"
mouse = false
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-messages = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'
"'" = "'"
